language: node_js
node_js:
   - "8"
branches:
   only:
      - master
script:
   - yarn install
   - yarn run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: /build
  on:
    branch: master